name = "pomodoro"
pages_build_output_dir = "./dist"
compatibility_date = "2026-02-02"
compatibility_flags = [ "nodejs_compat" ]

# âš¡ D1 Database Binding
# This allows your code to access the DB via `env.DB`
[[d1_databases]]
binding = "DB"
database_name = "pomodoro-db"
database_id = "896db0a5-ecfc-4f4d-92d2-302a54266f3d"

# ðŸ“¦ KV Namespace Binding (Cache de Sesiones)
[[kv_namespaces]]
binding = "LUCIA_KV"
id = "2f41dca3b1444beebacd5a4d94284baa"
